// src/App.tsx
import React, { useState } from 'react';
import { Menu, X, Github, Mail, Linkedin, Phone, BookOpen, Plane, Code, Building2, GraduationCap, Languages, PenTool as Tool } from 'lucide-react';

function App() {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Navigation */}
      <nav className="bg-white shadow-lg fixed w-full z-10">
        <div className="max-w-7xl mx-auto px-4">
          <div className="flex justify-between h-16">
            <div className="flex items-center">
              <span className="text-xl font-bold">Abdullah TAGARI</span>
            </div>
            
            {/* Mobile menu button */}
            <div className="flex items-center md:hidden">
              <button
                onClick={() => setIsMenuOpen(!isMenuOpen)}
                className="text-gray-700 hover:text-gray-900"
              >
                {isMenuOpen ? <X size={24} /> : <Menu size={24} />}
              </button>
            </div>

            {/* Desktop menu */}
            <div className="hidden md:flex md:items-center md:space-x-6">
              <a href="#about" className="text-gray-700 hover:text-gray-900">À propos</a>
              <a href="#experience" className="text-gray-700 hover:text-gray-900">Expérience</a>
              <a href="#education" className="text-gray-700 hover:text-gray-900">Formation</a>
              <a href="#skills" className="text-gray-700 hover:text-gray-900">Compétences</a>
              <a href="#contact" className="text-gray-700 hover:text-gray-900">Contact</a>
            </div>
          </div>
        </div>

        {/* Mobile menu */}
        {isMenuOpen && (
          <div className="md:hidden">
            <div className="px-2 pt-2 pb-3 space-y-1">
              <a href="#about" className="block px-3 py-2 text-gray-700 hover:text-gray-900">À propos</a>
              <a href="#experience" className="block px-3 py-2 text-gray-700 hover:text-gray-900">Expérience</a>
              <a href="#education" className="block px-3 py-2 text-gray-700 hover:text-gray-900">Formation</a>
              <a href="#skills" className="block px-3 py-2 text-gray-700 hover:text-gray-900">Compétences</a>
              <a href="#contact" className="block px-3 py-2 text-gray-700 hover:text-gray-900">Contact</a>
            </div>
          </div>
        )}
      </nav>

      {/* Main Content */}
      <main className="pt-16">
        {/* Hero Section */}
        <section className="bg-gradient-to-r from-blue-500 to-blue-700 text-white py-20">
          <div className="max-w-7xl mx-auto px-4 text-center">
            <h1 className="text-4xl md:text-5xl font-bold mb-4">Abdullah TAGARI</h1>
            <p className="text-xl md:text-2xl">Apprenti Développeur | Futur Ingénieur Informatique</p>
          </div>
        </section>

        {/* About Section */}
        <section id="about" className="py-16 bg-white">
          <div className="max-w-7xl mx-auto px-4">
            <h2 className="text-3xl font-bold mb-8 text-center">À Propos</h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div>
                <p className="text-gray-600 mb-4">
                  Je m'appelle Abdullah TAGARI, j'ai 19 ans et je suis un apprenti en informatique.
                  Mon objectif est d'acquérir de solides connaissances en développement d'applications
                  pour devenir ingénieur informatique.
                </p>
              </div>
              <div>
                <h3 className="text-xl font-semibold mb-4">Centres d'intérêts</h3>
                <div className="flex items-center mb-3">
                  <BookOpen className="mr-2" />
                  <span>Lectures : Mangas</span>
                </div>
                <div className="flex items-center">
                  <Plane className="mr-2" />
                  <span>Voyages : Royaume-Uni, Belgique, Allemagne, Espagne, Grèce, Italie, Émirats Arabes Unis, Turquie, Inde</span>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Experience Section */}
        <section id="experience" className="py-16 bg-gray-50">
          <div className="max-w-7xl mx-auto px-4">
            <h2 className="text-3xl font-bold mb-8 text-center">Expérience</h2>
            <div className="space-y-8">
              <div className="bg-white p-6 rounded-lg shadow-md">
                <div className="flex items-center mb-4">
                  <Code className="mr-2" />
                  <h3 className="text-xl font-semibold">Projets Universitaires</h3>
                </div>
                <p className="text-gray-600 mb-4">
                  • Refonte du site web d'une association (Alcool Ecoute Joie et Santé)<br />
                  • Développement d'une application mobile avec Android Java et Spring Boot
                </p>
              </div>
              
              <div className="bg-white p-6 rounded-lg shadow-md">
                <div className="flex items-center mb-4">
                  <Building2 className="mr-2" />
                  <h3 className="text-xl font-semibold">Projets Professionnels</h3>
                </div>
                <p className="text-gray-600">
                  • Refonte d'applications web avec Spring Boot et Vue.js<br />
                  • Développement d'outils de traitement de données
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Education Section */}
        <section id="education" className="py-16 bg-white">
          <div className="max-w-7xl mx-auto px-4">
            <h2 className="text-3xl font-bold mb-8 text-center">Formation</h2>
            <div className="bg-gray-50 p-6 rounded-lg shadow-md">
              <div className="flex items-center mb-4">
                <GraduationCap className="mr-2" />
                <h3 className="text-xl font-semibold">BUT Informatique</h3>
              </div>
              <p className="text-gray-600">
                IUT de Paris Rives de Seine - 2ème année en alternance<br />
                Apprenti à la RATP
              </p>
            </div>
          </div>
        </section>

        {/* Skills Section */}
        <section id="skills" className="py-16 bg-gray-50">
          <div className="max-w-7xl mx-auto px-4">
            <h2 className="text-3xl font-bold mb-8 text-center">Compétences</h2>
            <div className="grid md:grid-cols-2 gap-8">
              <div className="bg-white p-6 rounded-lg shadow-md">
                <div className="flex items-center mb-4">
                  <Code className="mr-2" />
                  <h3 className="text-xl font-semibold">Langages</h3>
                </div>
                <p className="text-gray-600">
                  HTML, CSS, JavaScript, PHP, Java, Android Java, Python, C/C++, SQL, Assembleur, VBA
                </p>
              </div>
              
              <div className="bg-white p-6 rounded-lg shadow-md">
                <div className="flex items-center mb-4">
                  <Tool className="mr-2" />
                  <h3 className="text-xl font-semibold">Outils</h3>
                </div>
                <p className="text-gray-600">
                  GitHub, Postman, Jetbrains, Eclipse, Android Studio, MySQL, MariaDB, VirtualBox, Cisco Packet Tracer, Power BI
                </p>
              </div>

              <div className="bg-white p-6 rounded-lg shadow-md">
                <div className="flex items-center mb-4">
                  <Languages className="mr-2" />
                  <h3 className="text-xl font-semibold">Langues</h3>
                </div>
                <p className="text-gray-600">
                  Français, Anglais, Espagnol, Gujarati
                </p>
              </div>
            </div>
          </div>
        </section>

        {/* Contact Section */}
        <section id="contact" className="py-16 bg-white">
          <div className="max-w-7xl mx-auto px-4">
            <h2 className="text-3xl font-bold mb-8 text-center">Contact</h2>
            <div className="flex justify-center space-x-8">
              <a href="#" className="flex items-center text-gray-600 hover:text-blue-600">
                <Mail className="mr-2" />
                <span>Email</span>
              </a>
              <a href="#" className="flex items-center text-gray-600 hover:text-blue-600">
                <Phone className="mr-2" />
                <span>Téléphone</span>
              </a>
              <a href="#" className="flex items-center text-gray-600 hover:text-blue-600">
                <Linkedin className="mr-2" />
                <span>LinkedIn</span>
              </a>
              <a href="#" className="flex items-center text-gray-600 hover:text-blue-600">
                <Github className="mr-2" />
                <span>GitHub</span>
              </a>
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-gray-800 text-white py-8">
        <div className="max-w-7xl mx-auto px-4 text-center">
          <p>© 2024 Abdullah TAGARI. Tous droits réservés.</p>
        </div>
      </footer>
    </div>
  );
}

export default App;

// src/App.vue
<template>
  <div class="min-h-screen">

    <!-- Navigation -->
    <nav class="bg-white shadow-md fixed w-full z-20 backdrop-blur-md">
      <div class="max-w-7xl mx-auto px-4">
        <div class="flex justify-between items-center h-16">
          <div class="flex items-center">
            <span class="text-2xl font-bold text-gray-800">
              Abdullah TAGARI
            </span>
          </div>
          <div class="flex items-center md:hidden">
            <button @click="isMenuOpen = !isMenuOpen" class="text-gray-700 hover:text-gray-900 focus:outline-none">
              <Menu v-if="!isMenuOpen" :size="24" />
              <X v-else :size="24" />
            </button>
          </div>
          <div class="hidden md:flex md:space-x-8">
            <a v-for="item in menuItems" :key="item.href" :href="item.href" @click.prevent="scrollTo(item.href)" class="nav-link">{{ item.text }}</a>
          </div>
        </div>
      </div>

      <div v-if="isMenuOpen" class="md:hidden">
        <div class="px-2 pt-2 pb-3 space-y-1">
          <a v-for="item in menuItems" :key="item.href" :href="item.href" @click.prevent="scrollTo(item.href)" class="block nav-link">{{ item.text }}</a>
        </div>
      </div>
    </nav>

    <!-- Main Content -->
    <main class="pt-20">

      <!-- Section 1: Étudiant en Informatique -->
      <section class="text-white py-16 text-center bg-blue-banner mt-8 mb-8 mx-4">
        <h2 class="text-4xl md:text-5xl font-bold">
          Étudiant en Informatique
        </h2>
      </section>


      <!-- Section 2: À Propos -->
      <section id="about" class="py-20 bg-white">
        <div class="max-w-7xl mx-auto px-4">
          <h2 class="section-title">À Propos</h2>
          <div class="grid md:grid-cols-2 gap-12">
            <div class="card">
              <h3 class="text-2xl font-semibold mb-6">Qui suis-je ?</h3>
              <p class="text-gray-700 leading-relaxed mb-4">
                Je m'appelle Abdullah TAGARI, 19 ans, apprenti en informatique.
                Mon objectif est de devenir ingénieur en développement d'applications.
              </p>
              <p class="text-gray-700 leading-relaxed">
                Passionné par les nouvelles technologies, l'innovation et le développement logiciel.
              </p>
            </div>
            <div class="card">
              <h3 class="text-2xl font-semibold mb-6">Centres d'intérêts</h3>
              <div class="space-y-4">
                <div class="flex items-center p-3 bg-gray-100 rounded-lg">
                  <BookOpen class="icon" />
                  <div>
                    <h4 class="font-semibold">Lectures</h4>
                    <p class="text-gray-600">Mangas</p>
                  </div>
                </div>
                <div class="flex items-center p-3 bg-gray-100 rounded-lg">
                  <Plane class="icon" />
                  <div>
                    <h4 class="font-semibold">Voyages</h4>
                    <p class="text-gray-600">Angleterre, Belgique, Allemagne, Espagne, Grèce, Italie, EAU, Turquie, Inde</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Section 3: Expériences -->
      <section id="experience" class="py-20 bg-gray-50">
        <div class="max-w-7xl mx-auto px-4">
          <h2 class="section-title">Expériences</h2>
          <div class="grid md:grid-cols-1 lg:grid-cols-3 gap-12 mt-10">
            <!-- Expériences Hors Informatique -->
            <div class="card">
              <div class="flex items-center mb-6">
                <Users class="icon" />
                <h3 class="text-2xl font-semibold">Expériences Hors Informatique</h3>
              </div>
              <ul class="text-gray-600 leading-relaxed space-y-4">
                <li>Service Client : Vente et conseil, développement des compétences en communication.</li>
                <li>JO 2024 : Saisonnier - vente de tickets, guide touristique, gestion des flux de voyageurs.</li>
              </ul>
            </div>

            <!-- Expériences informatiques -->
            <div class="card">
              <div class="flex items-center mb-6">
                <Code class="icon" />
                <h3 class="text-2xl font-semibold">Projets Universitaires</h3>
              </div>
              <p class="text-gray-600 leading-relaxed">
                Refonte de sites web et création d'applications mobiles en Android Java & Spring Boot.
              </p>
            </div>
            <div class="card">
              <div class="flex items-center mb-6">
                <Building2 class="icon" />
                <h3 class="text-2xl font-semibold">Projets Professionnels</h3>
              </div>
              <p class="text-gray-600 leading-relaxed">
                Modernisation d'applications, outils de traitement de données avec Spring Boot & Vue.js.
              </p>
            </div>
          </div>
        </div>
      </section>

      <!-- Section 4: Compétences -->
      <section id="competences" class="py-20 bg-white">
        <div class="max-w-7xl mx-auto px-4">
          <h2 class="section-title">Compétences Techniques</h2>
          <div class="grid md:grid-cols-3 gap-8 mt-12">
            <div class="card">
              <div class="flex items-center mb-6">
                <Code class="icon" />
                <h3 class="text-2xl font-semibold">Langages</h3>
              </div>
              <div class="flex flex-wrap gap-2">
                <span v-for="lang in languages" :key="lang" class="skill-tag">{{ lang }}</span>
              </div>
            </div>

            <div class="card">
              <div class="flex items-center mb-6">
                <Wrench class="icon" />
                <h3 class="text-2xl font-semibold">Outils</h3>
              </div>
              <div class="flex flex-wrap gap-2">
                <span v-for="tool in tools" :key="tool" class="skill-tag">{{ tool }}</span>
              </div>
            </div>

            <div class="card">
              <div class="flex items-center mb-6">
                <Languages class="icon" />
                <h3 class="text-2xl font-semibold">Langues Parlées</h3>
              </div>
              <div class="flex flex-wrap gap-2">
                <span v-for="spoken in spokenLanguages" :key="spoken" class="skill-tag">{{ spoken }}</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Section Contact -->
      <section id="contact" class="py-20 bg-gray-100">
        <div class="max-w-3xl mx-auto px-4 text-center">
          <h2 class="section-title">Contactez-moi</h2>
          <p class="text-gray-700 mb-8">Je suis disponible pour discuter de vos projets ou d'une opportunité professionnelle.</p>
          <div class="flex justify-center mt-6 gap-12"> <!-- Augmenté gap à 12 pour plus d'espace -->
            <div class="flex space-x-6 mt-4 gap-12"> <!-- Augmenté space-x à 6 pour plus d'espace entre les icônes -->
              <!-- Email -->
              <a href="mailto:tagariabdullah@gmail.com" class="text-gray-700 hover:text-gray-900">
                <Mail class="icon" />
              </a>
              <!-- Téléphone -->
              <a href="tel:+0782402766" class="text-gray-700 hover:text-gray-900">
                <Phone class="icon" />
              </a>
              <!-- LinkedIn -->
              <a href="https://www.linkedin.com/in/abdullahtagari" target="_blank" class="text-gray-700 hover:text-gray-900">
                <Linkedin class="icon" />
              </a>
              <!-- GitHub -->
              <a href="https://github.com/abdullah-tagari" target="_blank" class="text-gray-700 hover:text-gray-900">
                <Github class="icon" />
              </a>
            </div>
          </div>
        </div>
      </section>


    </main>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Menu, X, BookOpen, Plane, Code, Building2, Users, Languages, Wrench, Github, Linkedin, Phone, Mail } from 'lucide-vue-next'

const isMenuOpen = ref(false)

const menuItems = [
  { text: 'À propos', href: '#about' },
  { text: 'Expériences', href: '#experience' },
  { text: 'Compétences', href: '#competences' },
  { text: 'Contact', href: '#contact' },
]

const languages = [
  'HTML', 'CSS', 'JavaScript', 'PHP', 'Java', 'Android Java', 'Python', 'C/C++', 'SQL', 'Assembleur', 'VBA'
]

const tools = [
  'GitHub', 'Postman', 'Jetbrains', 'Eclipse', 'Android Studio', 'MySQL', 'MariaDB', 'VirtualBox', 'Cisco Packet Tracer', 'Power BI'
]

const spokenLanguages = [
  'Français', 'Anglais', 'Espagnol', 'Gujarati'
]

function scrollTo(selector: string) {
  const element = document.querySelector(selector)
  if (element) {
    element.scrollIntoView({ behavior: 'smooth' })
  }
  isMenuOpen.value = false
}
</script>

<style>
  /* Tu peux ajouter ici tes styles personnalisés */
</style>
